#!/bin/bash
domain=$1;
www="www.$domain";
conf="$domain.conf";
sapath="/etc/httpd/conf.d/$conf";

touch $sapath;
echo "<VirtualHost $2:80>
    ServerName $www
    ServerAlias $domain
    DocumentRoot /var/www/html/$domain/
    ErrorLog /var/www/html/$domain/error.log
    CustomLog /var/www/html/$domain/access.log combined
</VirtualHost>">$sapath;

apachectl restart;

